---
_zsh_base_config_templates:
  - src: p10k-nekeal.zsh.j2
    dest: .p10k.zsh

users:
  - username: "{{ _username }}"
    shell: /bin/zsh
    groups:
      - sudo
      - vboxusers 
      - docker
    zinit_plugins_template: zinit-plugins-nekeal.zsh.j2
    zshrc:
      template: zshrc-nekeal.zsh.j2
    aliases:
      template: aliases-nekeal.zsh
    zsh_config_templates: "{{ _zsh_base_config_templates + _zsh_extra_config_templates }}"
    env_vars:
      VIRTUALENVWRAPPER_PYTHON: /usr/bin/python3
      PROJECT_HOME: "/home/{{ _username }}/PycharmProjects"
      DOCKER_BUILDKIT: "1"
      COMPLETION_WAITING_DOTS: "true"
      NVM_AUTO_USE: "true" # used by nvm plugin
      skip_global_compinit: "true"

_extra_aliases: {}

git_version: "2.39.2"
git_install_from_source: true
git_install_from_source_force_update: true

apt_install_recommends: yes # whether or not to install the "recommended" packages by default
apt_default_packages:
  - unattended-upgrades
# Python build dependencies
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - curl
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev