roles:
  - nekeal.zsh
  - anxs.apt
  - geerlingguy.git
  - gantsign.visual-studio-code
  - name: darkwizard242.ansible-role-googlechrome
    src: https://github.com/darkwizard242/ansible-role-googlechrome
  - geerlingguy.docker