---
nekeal:
  ansible_connection: local
  hosts:
    nekeal_work:
      ansible_connection: local
      ansible_host: nekeal_work
    nekeal_home:
      ansible_connection: local
      ansible_host: nekeal_home
      ansible_python_interpreter: /usr/bin/python3